/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "fdmymfxzwadzvonwcvsp"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkbXltZnh6d2FkenZvbndjdnNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI0MzM1NTgsImV4cCI6MjA4ODAwOTU1OH0.8-Qm6-9Jy074E57thH5iE6KODp93ErU8rRyAVMd_tTc"